# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'instagramCloneApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for instagramCloneApp
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Firestore', '~> 5.15.0'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'FBSDKCoreKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git'
  pod 'FBSDKLoginKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git'
  pod 'FBSDKShareKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git'

  target 'instagramCloneAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'instagramCloneApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for instagramCloneApp-tvOS

  target 'instagramCloneApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
